package com.triocodes.krishikkaran.Enum;

/**
 * Created by admin on 07-03-16.
 */
public enum ServiceCallEnum {
ADDPRODUCT,YOURREQUIREMENTS,LOGIN,REGISTRATION,STATE,DISTRICT,POSTOFFICE,CATAGORY,QUANTITY,BARTER,YOURPRODUCTS,
    MODIFYYOURPRODUCTSAVE,DELETEYOURPRODUCT,BIDYOURPRODUCTADD,BIDYOURPRODUCTDELETE,MODIFYYOURPRODUCTDETAILS,MODIFYYOURPRODUCTBARTER,
    BIDYOURPRODUCTDETAILS,PRODUCTNAMESEARCHSCROLL,DISTRICTSEARCHSCROLL,LOCATIONSEARCHSCROLL,
    SELLERDETAILSVIEW,FRUITS,BIDPRODUCTDETAILS,BIDDETAILSADD,BARTERPRODUCTLIST,BARTERSEND,DISTRICTSEARCH,LOCATIONSEARCH,PRODUCTNAMESEARCH;
}
